### PR TITLE
32-bit bootloader: Real mode stuff

### PR DESCRIPTION
**Pull request by bendaws**
Following a basic structure provided by [wiki.osdev.org](https://wiki.osdev.org), I have constructed the most basic of bootloaders.

A lot of code was taken from my small [rinix](https://GitHub.com/olssonn/rinix) project.

## References
- [Bootloader - OSDev Wiki](https://wiki.osdev.org/Bootloader)
- [Bare bones - OSDev Wiki](https://wiki.osdev.org/Bare_Bones)

### CODE REVIEW

**Comment by Fivvee0** [comment]
Hey, idk if you read it but I invited in dm (on dc) to Project group

**Comment by olssonn** [comment]
> Hey, idk if you read it but I invited in dm (on dc) to Project group

I noticed, not at home right now
I also merged #9 since it is good for right now

**Comment by olssonn** [comment]
Fixed merge conflicts with #9 and main branch

**Comment by Fivvee0** [comment]
> > Hey, idk if you read it but I invited in dm (on dc) to Project group
> 
> I noticed, not at home right now I also merged #9 since it is good for right now

when you come home can you please join ?

**Comment by bendaws** [comment]
After reset, this PR no longer works

**Pull request closed without merging**
