### PR TITLE
Terminal support

### PR DESCRIPTION
**Pull request by olssonn**
This PR adds terminal emulator support. The default terminal will handle setting up and running your favorite shell environment, as well as handling input.

### CODE REVIEW

**Comment by Fivvee0** [comment]
wow that was a lot of work. thanks

**Comment by jamjellyfish** [comment]
This is still kind of a work in progress, there should be some way to switch terminal modes. Here is a rundown:

*nix systems have two modes: a regular terminal mode, and a "raw mode".

- Raw Mode will let the currently running application handle keypresses itself. Escape sequences like ^C are still handled by the machine, and it is what powers the favorites of text editors today like Vim, Emacs, and Nano.
- Regular Mode is what everyone is used to. It is usually assisted by a shell like Bash, and lets you do all the easy character handling like ``scanf()``.

Currently, I would like to add features that will assist in creating raw mode later, but focus on regular mode support now.

**Comment by Fivvee0** [comment]
Do you wanna be a member of the team because I can talk with others about it and then you can do it easier on other branch or something

**Comment by jamjellyfish** [comment]
> Do you wanna be a member of the team because I can talk with others about it and then you can do it easier on other branch or something

Possibly, I have a good amount of free time today

**Comment by jamjellyfish** [comment]
I included a pretty basic shell-starter for RawBerry in ``/include/rbsh``. It should be sufficient for what the goal is for terminal support right now. You can run ``about`` to see this:
```
redberry@rawberry : $ version
RawBerry Operating System v1.0.0
(C) Copyright 2024 RawBerry Team
Licensed under the MIT License
    
RawBerry Shell v1.0.0
(C) Copyright 2024 Ben Daws <ben@bendaws.net>
Licensed under the MIT License.
```

**Comment by Fivvee0** [comment]
it doesnt compile can you fix issues with compiling. thanks.

**Comment by jamjellyfish** [comment]
My bet is that terminal support will take way longer to make effective and working. I will go ahead and fix issues with compilation on my end.

**Comment by Fivvee0** [comment]
Okay. I am Talking with members of team to add you to team

**Pull request closed without merging**
