### PR TITLE
propose five versions support

### PR DESCRIPTION
**Pull request by Vexaited**
idk, i want simply to be a contributor and this support method will be fine for me

### CODE REVIEW

**Comment by Goldjakyt** [comment]
what is your discord nickname?

**Comment by Vexaited** [comment]
i can create discord account but i don't have; i browsed github for begginers oses and i found this

**Comment by Goldjakyt** [comment]
ok

**Comment by Vexaited** [comment]
must i create discord account?

**Comment by Goldjakyt** [comment]
Create discord account and join

**Comment by Vexaited** [comment]
okay, is there any link to a discord server or something

**Comment by Goldjakyt** [comment]
yes

**Comment by Goldjakyt** [comment]
yes

**Comment by Vexaited** [comment]
hi, thats me, discord username is .vexaited.

**Comment by Goldjakyt** [comment]
okay

**Pull request closed without merging**
