### PR TITLE
Added reported kernel version when booting

### PR DESCRIPTION
**Pull request by Mihot7**
Simple change :)

### CODE REVIEW

**Comment by Mihot7** [comment]
Also added character/font test

**Comment by Goldjakyt** [comment]
Have you checked if it works?

**Comment by Mihot7** [comment]
I can't since I'm on Windows, so building c code is pain, I can try it a bit later...

**Comment by Goldjakyt** [comment]
ok

**Comment by Mihot7** [comment]
Can you try it for me?

**Comment by Fivvee0** [comment]
There will be tests by github actions but for now we will test it

**Comment by Mihot7** [comment]
Thanks, please tell me if it works

**Comment by Goldjakyt** [comment]
Gorciu corrupted the file (probably because it was working before Gorciu committed) and now strange patterns appear

**Comment by Mihot7** [comment]
Can you send a screenshot please?

**Comment by gorciu-official** [comment]
> Gorciu corrupted the file (probably because it was working before Gorciu committed) and now strange patterns appear
I don't know why, i didn't change the code

**Comment by Goldjakyt** [comment]
> > Gorciu corrupted the file (probably because it was working before Gorciu committed) and now strange patterns appear
> > I don't know why, i didn't change the code

a naprawisz to?

**Comment by Mihot7** [comment]
Czekaj, tu można po polsku?

**Comment by Goldjakyt** [comment]
polski i angielski

**Comment by Mihot7** [comment]
Aha

**Comment by Goldjakyt** [comment]
ale preferuje angielski poprostu nie chcialo mi sie pisac

**Comment by Mihot7** [comment]
Aha

**Comment by Fivvee0** [comment]
Please if you can talk in english

**Comment by Mihot7** [comment]
I can, I'm fluent in English...

**Comment by Goldjakyt** [comment]
dobra na discorda wszyscy bo to nie miejsce do gadania tylko do komentowania pull requestow

**Comment by Mihot7** [comment]
Bruh 😭

**Pull request closed without merging**
